const traductor = {
    // ----------------------------------------------------
    // 1. MÚSCULOS Y PARTES DEL CUERPO (Inglés a Español)
    // ----------------------------------------------------
    "abductors": "abductores",
    "abs": "abdomen",
    "adductors": "aductores",
    "biceps": "bíceps",
    "calves": "pantorrillas",
    "cardiovascular system": "sistema cardiovascular",
    "cardio": "cardio",
    "chest": "pecho",
    "delts": "deltoides",
    "forearms": "antebrazos",
    "glutes": "glúteos",
    "hamstrings": "isquiotibiales",
    "lats": "dorsales",
    "levator scapulae": "elevador de la escápula",
    "lower arms": "antebrazos",
    "lower back": "espalda baja",
    "lower legs": "pantorrillas",
    "neck": "cuello",
    "obliques": "oblicuos",
    "pectorals": "pectorales",
    "quads": "cuádriceps",
    "serratus anterior": "serrato anterior",
    "shoulders": "hombros",
    "spine": "columna",
    "traps": "trapecios",
    "triceps": "tríceps",
    "upper arms": "brazos",
    "upper back": "espalda alta",
    "upper legs": "piernas",
    "back": "espalda",
    "waist": "cintura",

    // ----------------------------------------------------
    // 2. EQUIPAMIENTO (Inglés a Español)
    // ----------------------------------------------------
    "assisted": "asistido",
    "band": "banda de resistencia",
    "barbell": "barra",
    "battle rope": "cuerdas de batalla",
    "body weight": "peso corporal",
    "bosu ball": "balón bosu",
    "cable": "polea",
    "dumbbell": "mancuerna",
    "elliptical machine": "elíptica",
    "ez barbell": "barra ez",
    "hammer": "martillo",
    "kettlebell": "pesa rusa",
    "leverage machine": "máquina de palanca",
    "machine": "máquina",
    "medicine ball": "balón medicinal",
    "olympic barbell": "barra olímpica",
    "resistance band": "banda elástica",
    "roller": "rodillo",
    "rope": "cuerda",
    "skierg machine": "máquina skierg",
    "sled machine": "trineo",
    "smith machine": "máquina smith",
    "stability ball": "pelota suiza",
    "stationary bike": "bicicleta estática",
    "stepboard": "step",
    "suspension": "trx (suspensión)",
    "tire": "llanta",
    "trap bar": "barra hexagonal",
    "upper body ergometer": "ergómetro de brazos",
    "weight": "disco de peso",

    // ----------------------------------------------------
    // 3. BÚSQUEDAS DEL USUARIO (Español a Inglés)
    // Para engañar a la API cuando el usuario escriba en español
    // ----------------------------------------------------
    "espalda": "back",
    "pecho": "chest",
    "pierna": "upper leg",
    "piernas": "upper leg",
    "brazo": "upper arm",
    "brazos": "upper arm",
    "hombro": "shoulders",
    "hombros": "shoulders",
    "abdomen": "waist",
    "abdominales": "abs",
    "pantorrilla": "calves",
    "pantorrillas": "calves",
    "gluteo": "glutes",
    "glúteo": "glutes",
    "gluteos": "glutes",
    "glúteos": "glutes",
    "tricep": "triceps",
    "tríceps": "triceps",
    "bicep": "biceps",
    "bíceps": "biceps",
    "mancuerna": "dumbbell",
    "mancuernas": "dumbbell",
    "barra": "barbell",
    "polea": "cable",
    "poleas": "cable",
    "maquina": "machine",
    "máquina": "machine",
    "peso corporal": "body weight",
    "banda": "band"
};
export { traductor };